def make_issue(title, priority, labels, problem, fix):
    return {
        "title": title,
        "priority": priority,
        "labels": labels,
        "problem": problem,
        "fix": fix,
    }


def planner_agent(state):
    structure = state.get("structure_report", {})
    docs = state.get("docs_report", {})
    code = state.get("code_report", {})
    security = state.get("security_report", {})
    merged = state.get("merged_report", {})

    issues = []

    for name, passed in structure.get("checks", {}).items():
        if not passed:
            issues.append(make_issue(
                f"Improve project structure: {name}",
                "medium",
                ["structure", "repo-quality"],
                f"The structure check failed: {name}.",
                "Add the missing file/folder or improve the repository organization."
            ))

    for name, passed in docs.get("checks", {}).items():
        if not passed:
            issues.append(make_issue(
                f"Improve documentation: {name}",
                "medium",
                ["documentation", "readme"],
                f"The documentation check failed: {name}.",
                f"Add a clear {name} section to the README or docs folder."
            ))

    for item in code.get("large_files", []):
        issues.append(make_issue(
            f"Refactor large file: {item['file']}",
            "low",
            ["refactor", "code-quality"],
            f"{item['file']} has {item['lines']} lines.",
            "Split the file into smaller modules with focused responsibilities."
        ))

    for finding in security.get("findings", []):
        issues.append(make_issue(
            f"Review possible secret keyword in {finding['file']}",
            "high",
            ["security", "audit"],
            f"Found secret-like keyword: {finding['pattern']}.",
            "Verify that no real credentials are committed and move secrets to environment variables."
        ))

    if not issues:
        issues.append(make_issue(
            "Add architecture diagram",
            "low",
            ["documentation", "enhancement"],
            "The repository is strong, but a diagram would improve onboarding.",
            "Add docs/architecture.md with a simple module-level diagram."
        ))

    for rec in merged.get("recommendations", []):
        if len(issues) >= 10:
            break

        issues.append(make_issue(
            rec,
            "medium",
            ["improvement"],
            "This recommendation was generated by the merged multi-agent analysis.",
            rec
        ))

    return {
        **state,
        "issues": issues[:10]
    }